# This file has been autogenerated by the pywayland scanner

# Copyright © 2008-2011 Kristian Høgsberg
# Copyright © 2010-2011 Intel Corporation
# Copyright © 2012-2013 Collabora, Ltd.
# Copyright © 2012, 2013 Intel Corporation
# Copyright © 2015, 2016 Jan Arne Petersen
# Copyright © 2017, 2018 Red Hat, Inc.
# Copyright © 2018       Purism SPC
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

from __future__ import annotations

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from ..wayland import WlSeat
from .zwp_input_method_v2 import ZwpInputMethodV2


class ZwpInputMethodManagerV2(Interface):
    """Input method manager

    The input method manager allows the client to become the input method on a
    chosen seat.

    No more than one input method must be associated with any seat at any given
    time.
    """

    name = "zwp_input_method_manager_v2"
    version = 1


class ZwpInputMethodManagerV2Proxy(Proxy[ZwpInputMethodManagerV2]):
    interface = ZwpInputMethodManagerV2

    @ZwpInputMethodManagerV2.request(
        Argument(ArgumentType.Object, interface=WlSeat),
        Argument(ArgumentType.NewId, interface=ZwpInputMethodV2),
    )
    def get_input_method(self, seat: WlSeat) -> Proxy[ZwpInputMethodV2]:
        """Request an input method object

        Request a new input
        :class:`~pywayland.protocol.input_method_unstable_v2.ZwpInputMethodV2`
        object associated with a given seat.

        :param seat:
        :type seat:
            :class:`~pywayland.protocol.wayland.WlSeat`
        :returns:
            :class:`~pywayland.protocol.input_method_unstable_v2.ZwpInputMethodV2`
        """
        input_method = self._marshal_constructor(0, ZwpInputMethodV2, seat)
        return input_method

    @ZwpInputMethodManagerV2.request()
    def destroy(self) -> None:
        """Destroy the input method manager

        Destroys the :class:`ZwpInputMethodManagerV2` object.

        The
        :class:`~pywayland.protocol.input_method_unstable_v2.ZwpInputMethodV2`
        objects originating from it remain valid.
        """
        self._marshal(1)
        self._destroy()


class ZwpInputMethodManagerV2Resource(Resource):
    interface = ZwpInputMethodManagerV2


class ZwpInputMethodManagerV2Global(Global):
    interface = ZwpInputMethodManagerV2


ZwpInputMethodManagerV2._gen_c()
ZwpInputMethodManagerV2.proxy_class = ZwpInputMethodManagerV2Proxy
ZwpInputMethodManagerV2.resource_class = ZwpInputMethodManagerV2Resource
ZwpInputMethodManagerV2.global_class = ZwpInputMethodManagerV2Global
