# This file has been autogenerated by the pywayland scanner

# Copyright © 2008-2011 Kristian Høgsberg
# Copyright © 2010-2011 Intel Corporation
# Copyright © 2012-2013 Collabora, Ltd.
# Copyright © 2012, 2013 Intel Corporation
# Copyright © 2015, 2016 Jan Arne Petersen
# Copyright © 2017, 2018 Red Hat, Inc.
# Copyright © 2018       Purism SPC
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

from __future__ import annotations

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)


class ZwpInputPopupSurfaceV2(Interface):
    """Popup surface

    This interface marks a surface as a popup for interacting with an input
    method.

    The compositor should place it near the active text input area. It must be
    visible if and only if the input method is in the active state.

    The client must not destroy the underlying
    :class:`~pywayland.protocol.wayland.WlSurface` while the
    :class:`ZwpInputPopupSurfaceV2` object exists.
    """

    name = "zwp_input_popup_surface_v2"
    version = 1


class ZwpInputPopupSurfaceV2Proxy(Proxy[ZwpInputPopupSurfaceV2]):
    interface = ZwpInputPopupSurfaceV2

    @ZwpInputPopupSurfaceV2.request()
    def destroy(self) -> None:
        """destroy
        """
        self._marshal(0)
        self._destroy()


class ZwpInputPopupSurfaceV2Resource(Resource):
    interface = ZwpInputPopupSurfaceV2

    @ZwpInputPopupSurfaceV2.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def text_input_rectangle(self, x: int, y: int, width: int, height: int) -> None:
        """Set text input area position

        Notify about the position of the area of the text input expressed as a
        rectangle in surface local coordinates.

        This is a hint to the input method telling it the relative position of
        the text being entered.

        :param x:
        :type x:
            `ArgumentType.Int`
        :param y:
        :type y:
            `ArgumentType.Int`
        :param width:
        :type width:
            `ArgumentType.Int`
        :param height:
        :type height:
            `ArgumentType.Int`
        """
        self._post_event(0, x, y, width, height)


class ZwpInputPopupSurfaceV2Global(Global):
    interface = ZwpInputPopupSurfaceV2


ZwpInputPopupSurfaceV2._gen_c()
ZwpInputPopupSurfaceV2.proxy_class = ZwpInputPopupSurfaceV2Proxy
ZwpInputPopupSurfaceV2.resource_class = ZwpInputPopupSurfaceV2Resource
ZwpInputPopupSurfaceV2.global_class = ZwpInputPopupSurfaceV2Global
